-- V1__Initial_setup.sql

-- tb_department
CREATE TABLE tb_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

-- tb_role
CREATE TABLE tb_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    authority VARCHAR(255),
    PRIMARY KEY (id)
);

-- tb_user
CREATE TABLE tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    is_active BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    dep_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (dep_id) REFERENCES tb_department(id)
);

-- tb_user_role
CREATE TABLE tb_user_role (
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, user_id),
    FOREIGN KEY (role_id) REFERENCES tb_role(id),
    FOREIGN KEY (user_id) REFERENCES tb_user(id)
);

-- alter table
ALTER TABLE tb_user_role
   ADD CONSTRAINT FKea2ootw6b6bb0xt3ptl28bymv FOREIGN KEY (role_id) REFERENCES tb_role(id);

ALTER TABLE tb_user_role
   ADD CONSTRAINT FK7vn3h53d0tqdimm8cp45gc0kl FOREIGN KEY (user_id) REFERENCES tb_user(id);
